/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProducoesRouteImport } from './routes/producoes'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnviarProjetoRouteImport } from './routes/enviar-projeto'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConteudoIndexRouteImport } from './routes/conteudo.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjetosProjetoIdRouteImport } from './routes/projetos.$projetoId'
import { Route as ConteudoSlugRouteImport } from './routes/conteudo.$slug'
import { Route as AdminConteudoIndexRouteImport } from './routes/admin.conteudo.index'
import { Route as AdminProjetosProjetoIdRouteImport } from './routes/admin.projetos.$projetoId'
import { Route as AdminConteudoPostIdRouteImport } from './routes/admin.conteudo.$postId'

const ProducoesRoute = ProducoesRouteImport.update({
  id: '/producoes',
  path: '/producoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarProjetoRoute = EnviarProjetoRouteImport.update({
  id: '/enviar-projeto',
  path: '/enviar-projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoIndexRoute = ConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjetosProjetoIdRoute = ProjetosProjetoIdRouteImport.update({
  id: '/projetos/$projetoId',
  path: '/projetos/$projetoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoSlugRoute = ConteudoSlugRouteImport.update({
  id: '/conteudo/$slug',
  path: '/conteudo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudoIndexRoute = AdminConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetosProjetoIdRoute = AdminProjetosProjetoIdRouteImport.update({
  id: '/projetos/$projetoId',
  path: '/projetos/$projetoId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoPostIdRoute = AdminConteudoPostIdRouteImport.update({
  id: '/conteudo/$postId',
  path: '/conteudo/$postId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/enviar-projeto': typeof EnviarProjetoRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRoute
  '/producoes': typeof ProducoesRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/projetos/$projetoId': typeof ProjetosProjetoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/admin/conteudo/$postId': typeof AdminConteudoPostIdRoute
  '/admin/projetos/$projetoId': typeof AdminProjetosProjetoIdRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/enviar-projeto': typeof EnviarProjetoRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRoute
  '/producoes': typeof ProducoesRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/projetos/$projetoId': typeof ProjetosProjetoIdRoute
  '/admin': typeof AdminIndexRoute
  '/conteudo': typeof ConteudoIndexRoute
  '/admin/conteudo/$postId': typeof AdminConteudoPostIdRoute
  '/admin/projetos/$projetoId': typeof AdminProjetosProjetoIdRoute
  '/admin/conteudo': typeof AdminConteudoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/enviar-projeto': typeof EnviarProjetoRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRoute
  '/producoes': typeof ProducoesRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/projetos/$projetoId': typeof ProjetosProjetoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/admin/conteudo/$postId': typeof AdminConteudoPostIdRoute
  '/admin/projetos/$projetoId': typeof AdminProjetosProjetoIdRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/empresas'
    | '/enviar-projeto'
    | '/login'
    | '/membros'
    | '/producoes'
    | '/conteudo/$slug'
    | '/projetos/$projetoId'
    | '/admin/'
    | '/conteudo/'
    | '/admin/conteudo/$postId'
    | '/admin/projetos/$projetoId'
    | '/admin/conteudo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empresas'
    | '/enviar-projeto'
    | '/login'
    | '/membros'
    | '/producoes'
    | '/conteudo/$slug'
    | '/projetos/$projetoId'
    | '/admin'
    | '/conteudo'
    | '/admin/conteudo/$postId'
    | '/admin/projetos/$projetoId'
    | '/admin/conteudo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/empresas'
    | '/enviar-projeto'
    | '/login'
    | '/membros'
    | '/producoes'
    | '/conteudo/$slug'
    | '/projetos/$projetoId'
    | '/admin/'
    | '/conteudo/'
    | '/admin/conteudo/$postId'
    | '/admin/projetos/$projetoId'
    | '/admin/conteudo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmpresasRoute: typeof EmpresasRoute
  EnviarProjetoRoute: typeof EnviarProjetoRoute
  LoginRoute: typeof LoginRoute
  MembrosRoute: typeof MembrosRoute
  ProducoesRoute: typeof ProducoesRoute
  ConteudoSlugRoute: typeof ConteudoSlugRoute
  ProjetosProjetoIdRoute: typeof ProjetosProjetoIdRoute
  ConteudoIndexRoute: typeof ConteudoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/producoes': {
      id: '/producoes'
      path: '/producoes'
      fullPath: '/producoes'
      preLoaderRoute: typeof ProducoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar-projeto': {
      id: '/enviar-projeto'
      path: '/enviar-projeto'
      fullPath: '/enviar-projeto'
      preLoaderRoute: typeof EnviarProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/': {
      id: '/conteudo/'
      path: '/conteudo'
      fullPath: '/conteudo/'
      preLoaderRoute: typeof ConteudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projetos/$projetoId': {
      id: '/projetos/$projetoId'
      path: '/projetos/$projetoId'
      fullPath: '/projetos/$projetoId'
      preLoaderRoute: typeof ProjetosProjetoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/$slug': {
      id: '/conteudo/$slug'
      path: '/conteudo/$slug'
      fullPath: '/conteudo/$slug'
      preLoaderRoute: typeof ConteudoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudo/': {
      id: '/admin/conteudo/'
      path: '/conteudo'
      fullPath: '/admin/conteudo/'
      preLoaderRoute: typeof AdminConteudoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projetos/$projetoId': {
      id: '/admin/projetos/$projetoId'
      path: '/projetos/$projetoId'
      fullPath: '/admin/projetos/$projetoId'
      preLoaderRoute: typeof AdminProjetosProjetoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/$postId': {
      id: '/admin/conteudo/$postId'
      path: '/conteudo/$postId'
      fullPath: '/admin/conteudo/$postId'
      preLoaderRoute: typeof AdminConteudoPostIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConteudoPostIdRoute: typeof AdminConteudoPostIdRoute
  AdminProjetosProjetoIdRoute: typeof AdminProjetosProjetoIdRoute
  AdminConteudoIndexRoute: typeof AdminConteudoIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminConteudoPostIdRoute: AdminConteudoPostIdRoute,
  AdminProjetosProjetoIdRoute: AdminProjetosProjetoIdRoute,
  AdminConteudoIndexRoute: AdminConteudoIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EmpresasRoute: EmpresasRoute,
  EnviarProjetoRoute: EnviarProjetoRoute,
  LoginRoute: LoginRoute,
  MembrosRoute: MembrosRoute,
  ProducoesRoute: ProducoesRoute,
  ConteudoSlugRoute: ConteudoSlugRoute,
  ProjetosProjetoIdRoute: ProjetosProjetoIdRoute,
  ConteudoIndexRoute: ConteudoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
