// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrtvuykothcsckosfelt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydHZ1eWtvdGhjc2Nrb3NmZWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNjAyMjcsImV4cCI6MjA5MTgzNjIyN30.5GV9Yy52vWR9Oon5mA43T8PFuiLA3cC7orC2ehRYSyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});